name: publish to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.3.0
      with:
        PROJECT_FILE_PATH: MakeAC.csproj
        NUGET_KEY: ${{ secrets.nuget_key }}
